<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\Portal\Doctrine\Controller;

use MSBios\Application\Controller\IndexController as DefaultIndexController;

/**
 * Class IndexController
 * @package MSBios\Portal\Doctrine\Controller
 */
class IndexController extends DefaultIndexController
{
    /**
     * @return \Zend\View\Model\ViewModel
     */
    public function indexAction()
    {
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }

}