<?php

return [
    // Retrieve list of modules used in this application.
    'modules' => [
        'MSBios\Test',
        'MSBios\Portal',
        'MSBios\Application',
        'MSBios\Theme',
        'Zend\I18n',
        'Zend\Navigation',
        'MSBios\Form',
        'Zend\Cache',
        'Zend\Paginator',
        'Zend\Mvc\Plugin\FilePrg',
        'Zend\Mvc\Plugin\Identity',
        'Zend\Mvc\Plugin\Prg',
        'Zend\Mvc\Plugin\FlashMessenger',
        'Zend\Form',
        'Zend\InputFilter',
        'Zend\Filter',
        'Zend\Hydrator',
        'Zend\Session',
        'Zend\Router',
        'Zend\Validator',
        'DoctrineModule',
        'DoctrineORMModule',
        'DoctrineDataFixtureModule',
        'MSBios\Assetic',
        'MSBios\View',
        'MSBios\Doctrine',
        'MSBios\Monolog',
        'MSBios\I18n',
        'MSBios\Widget',
        'MSBios\Resource',
        'MSBios\Navigation',
        'MSBios\Authentication',
        'MSBios\Guard',
        'MSBios\Guard\Resource',
        'MSBios\Guard\CPanel',
        'MSBios\CPanel',
        'MSBios\Authentication\Doctrine',
        'MSBios\Guard\CPanel\Doctrine',
        'MSBios\Guard\Resource\Doctrine',
        'MSBios\Resource\Doctrine',
        'MSBios\Form\Doctrine',
        'MSBios\CPanel\Doctrine',


//        'MSBios\Portal',
//        'MSBios\Application',
//        'MSBios\Theme',
//        'MSBios\Widget',
//        'MSBios\Assetic',
//        'MSBios\I18n',
//        'Zend\I18n',
//        'MSBios\Navigation',
//        'Zend\Navigation',
//        'MSBios\CPanel',
//        'Zend\Mvc\Plugin\FilePrg',
//        'Zend\Mvc\Plugin\Identity',
//        'Zend\Mvc\Plugin\Prg',
//        'Zend\Mvc\Plugin\FlashMessenger',
//        'MSBios\Guard\Resource\Doctrine',
//        'Zend\Session',
//        'MSBios\Form\Doctrine',
//        'MSBios\Doctrine',
//        'Zend\Cache',
//        'Zend\Paginator',
//        'Zend\Router',
//        'MSBios\Form',
//        'Zend\Form',
//        'Zend\InputFilter',
//        'Zend\Filter',
//        'Zend\Validator',
//        'Zend\Hydrator',
//        'DoctrineModule',
//        'DoctrineORMModule',

        'Zend\Log',
        'ZendDeveloperTools',
    ],

    'module_listener_options' => [
        'module_paths' => [
            './module',
            './vendor',
        ],
        'config_glob_paths' => [
            realpath(__DIR__) . '/autoload/{{,*.}global,{,*.}local}.php',
        ],
        'config_cache_enabled' => false,
        // 'config_cache_key' => 'application.config.cache',
        'module_map_cache_enabled' => false,
        // 'module_map_cache_key' => 'application.module.cache',
        'cache_dir' => 'data/cache/',
    ]
];
